# Generated by Django 3.2.1 on 2021-05-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('contacted', models.BooleanField(default=False)),
                ('interviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
